#!/bin/bash
DIR=$(pwd)			


if  [[ "$1" =~ ^[0-9]+$ ]]		
then
	if ! [[ "$2" =~ ^[0-9]+$ ]]
	then
		echo "Error in inputs. Must be an Integer.."
	else
		if ! [[ "$3" =~ ^[0-9]+$ ]]
		then
			echo "Error in inputs. Must be an Integer.."
		else

			if ! [[ "$4" =~ ^[0-9]+$ ]]
			then
				echo "Error in inputs. Must be an Integer.."
			else
				echo "Running project.."

				echo "CMake Building .."
				cd Multi_Thread_Bloom_Filter
				cd build
				cmake ..
				echo "CMake Build done"
				echo "Build project..."
				make
				echo "Build done..."

				./invoke-oracle-multithreaded "$1" "$2" "$3" "$4" "$5"
			fi
		fi
	fi

else
	if [ "$1" == "clean" ] 
	then
		echo "Clean up.."
		rm -rfv Multi_Thread_Bloom_Filter/build/*
	else
		echo "Wrong input "
	fi
fi


