#ifndef DELAY_TIME_H
#define DELAY_TIME_H

#define PAINTER_TIME_PART1_MS 2
#define PAINTER_TIME_PART2_MS 3
#define PAINTER_TIME_PART3_MS 5

#define CONTROL_TIME_PART1_MS 6
#define CONTROL_TIME_PART2_MS 8
#define CONTROL_TIME_PART3_MS 10

#endif
